config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books' => 'books#index'
  get '/campus/:campu_id/books/confirm' => 'books#confirm', as: 'book_confirm'
  get '/campus/:campu_id/books' => 'books#campus_index'
  get '/users/:user_id/checkouts' => 'checkouts#user_index', as: 'user_checkouts'
  get '/campus/:campu_id/checkouts' => 'checkouts#campus_index', as: 'campus_checkouts'
  get '/users/:user_id/check_in' => 'checkouts#check_in', as: 'user_check_in'
  get '/books/:book_id/reservations' => 'reservations#book_index', as: 'book_reservations'
  get '/users/:user_id/reservations' => 'reservations#user_index', as: 'user_reservations'
  get '/users/purchase_requests' => 'purchase_requests#user_index', as: 'user_purchase_requests'
  get '/books/search' => 'books#search', as: 'books_search'
  get '/books/results' => 'books#results', as: 'books_results'

  devise_for :users, :controllers => { :registrations => 'plock' }

  resources :campus do
    resources :books, except: [:index], shallow: true do
      resources :reviews, except: [:show, :index], shallow: true
      resources :checkouts, except: [:destroy, :new, :edit], shallow: true
      resources :reservations, only: [:create, :destroy], shallow: true
    end
    resources :purchase_requests, shallow: true
  end

  resources :users, only: [:index, :show]

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/purchase_request.rb
class PurchaseRequest < ActiveRecord::Base

  validates_presence_of :isbn,
                        :user_id,
                        :campus_id,
                        :status

  belongs_to :user
  belongs_to :campus

end

app/controllers/purchase_requests_controller.rb
class PurchaseRequestsController < ApplicationController

  def index
    @campus = Campus.find params[:campu_id]
    @prs = PurchaseRequest.where(campus_id: params[:campu_id], status: "pending").includes(:user)
    @prs_past = PurchaseRequest.where(campus_id: params[:campu_id]).where.not(status: "pending")
  end

  def user_index
    @prs = current_user.purchase_requests.all
  end

  def new
    @campus = Campus.find params[:campu_id]
    @pr = @campus.purchase_requests.new
  end

  def create
    @pr = current_user.purchase_requests.new approved_params
    gb = GetBook.new @pr.isbn
    book = gb.title_author
    @pr.title = book.first
    @pr.author = book.last
    @pr.status = "pending"
    if @pr.save
      flash[:notice] = "Purchase Request Made!"
      redirect_to campus_path
    else
      render :new
    end
  end

  def edit
    @pr = PurchaseRequest.find(params[:id])
  end

  def update
    @pr = PurchaseRequest.find(params[:id])
    if @pr.update approved_params
      if approved_params[:status] == 'purchased'
        gb = GetBook.new(@pr.isbn)
        book = gb.find
        redirect_to book_confirm_path(@pr.campus_id, isbn: book.isbn)
      else
        flash[:notice] = "Purchase Request updated!"
        redirect_to campu_purchase_requests_path(@pr.campus_id)
      end
    else
      render :edit
    end
  end

  private

  def approved_params
    params.require(:purchase_request).permit(:isbn, :klass, :campus_id, :status)
  end
end

app/views/purchase_requests/edit.html.erb
<h4>Edit Purchase Request #<%= @pr.id %></h4>
<p>Title: <%= @pr.title %>
  <br>Author: <%= @pr.author %>
  <br>ISBN: <%= @pr.isbn %>
  <br>For Class: <%= @pr.klass %>
  <br>Requested By: <%= @pr.user.email %>
</p>
<%= bootstrap_form_for @pr, url: purchase_request_path(@pr), method: :patch do |f| %>
  <%= f.select :status,
            options_for_select([['Purchased', 'purchased'],
                                ['Denied', 'denied']]), :include_blank => 'Select Status' %>
  <button class="btn btn-primary btn-sm">Submit</button>
<% end %>

app/views/purchase_requests/index.html.erb
<h2>
  Active Purchase Requests for <%= @campus.city %>
  <span class="badge"><%= @prs.count %></span>
</h2>

<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Book Author</th>
      <th>Book ISBN</th>
      <th>Subject Area</th>
      <th>Made By</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @prs.each do |p| %>
    </tr>
      <th><%= p.title %></th>
      <th><%= p.author %></th>
      <th><%= p.isbn %></th>
      <th><%= p.klass %></th>
      <th><%= p.user.email %></th>
      <th><%= p.status %></th>
      <th class="button-container">
        <%= button_to('Edit', edit_purchase_request_path(p), class: 'btn btn-xs btn-primary', method: :get) %>
      </th>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>
  Inactive Purchase Requests for <%= @campus.city %>
  <span class="badge"><%= @prs_past.count %></span>
</h2>

<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Book ISBN</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @prs_past.each do |p| %>
    </tr>
      <th><%= p.title %></th>
      <th><%= p.isbn %></th>
      <th><%= p.status %></th>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/purchase_requests/new.html.erb
<h4>Request a book for TIY <%= @campus.city %></h4>
<%= bootstrap_form_for @pr, url: campu_purchase_requests_path, method: :post do |f| %>
  <%= f.text_field :isbn, label: "ISBN number (no dashes)" %>
  <%= f.select :klass,
            options_for_select([['Rails', 'rails'],
                                ['Python', 'python'],
                                ['C#', 'c#'],
                                ['Front End', 'front end'],
                                ['User Interface', 'user interface'],
                                ['Java', 'java'],
                                ['Mobile', 'mobile']]), :include_blank => 'Select Class' , label: "Class"%>
  <%= f.hidden_field :campus_id, value: @campus.id %>
  <button class="btn btn-primary btn-sm">Submit</button>
<% end %>

app/views/purchase_requests/user_index.html.erb
<h2>
  Purchase Requests for <%= current_user.name %>
  <span class="badge"><%= @prs.count %></span>
</h2>

<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th>Book Title</th>
      <th>Book Author</th>
      <th>Book ISBN</th>
      <th>Subject Area</th>
      <th>Made By</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @prs.each do |p| %>
    </tr>
      <th><%= p.title %></th>
      <th><%= p.author %></th>
      <th><%= p.isbn %></th>
      <th><%= p.klass %></th>
      <th><%= p.user.email %></th>
      <th><%= p.status %></th>
    </tr>
    <% end %>
  </tbody>
</table>