config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books' => 'books#index'
  get '/campus/:campu_id/books/confirm' => 'books#confirm', as: 'book_confirm'
  get '/campus/:campu_id/books' => 'books#campus_index'
  get '/users/:user_id/checkouts' => 'checkouts#user_index', as: 'user_checkouts'
  get '/campus/:campu_id/checkouts' => 'checkouts#campus_index', as: 'campus_checkouts'
  get '/users/:user_id/check_in' => 'checkouts#check_in', as: 'user_check_in'
  get '/books/:book_id/reservations' => 'reservations#book_index', as: 'book_reservations'
  get '/users/:user_id/reservations' => 'reservations#user_index', as: 'user_reservations'
  get '/users/purchase_requests' => 'purchase_requests#user_index', as: 'user_purchase_requests'
  get '/books/search' => 'books#search', as: 'books_search'
  get '/books/results' => 'books#results', as: 'books_results'

  devise_for :users, :controllers => { :registrations => 'plock' }

  resources :campus do
    resources :books, except: [:index], shallow: true do
      resources :reviews, except: [:show, :index], shallow: true
      resources :checkouts, except: [:destroy, :new, :edit], shallow: true
      resources :reservations, only: [:create, :destroy], shallow: true
    end
    resources :purchase_requests, shallow: true
  end

  resources :users, only: [:index, :show]

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validates_presence_of :slack_name,
  #                       :type,
  #                       :klass,
  #                       :campus_id

  validates_uniqueness_of :slack_name, scope: :campus_id


  belongs_to :campus
  has_many :checkouts
  has_many :purchase_requests
  has_many :reviews
  has_many :reservations

  def has_reservation? book
    self.reservations.where(book: book)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find params[:id]
  end

  def index
    @users = User.all.includes(:campus).order(:campus_id)
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: "#{@user.name} deleted!" }
      format.json { render json: { status: :ok} }
    end
  end
end

app/views/users/index.html.erb
<body class="UserIndex">

  <h2>
    Current Users
    <span class="badge" id="user-count"></span>
  </h2>

  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Campus</th>
        <th>Class</th>
        <th>Slack Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |u| %>
      </tr>
        <th><%= u.name %></th>
        <th><%= u.email %></th>
        <th><%= u.campus.city %></th>
        <th><%= u.klass %></th>
        <th><%= u.slack_name %></th>
      </tr>
      <% end %>
      </tbody>
  </table>

</body>

app/views/users/show.html.erb
<h2>Account Options</h2>

<h4>Update Account Information</h4>
<%= link_to "Update Account Information", edit_user_registration_path %>

<h4>See Your Checkout History</h4>
<%= link_to "Checkout History", user_checkouts_path(@user) %>

<h4>Check In a Book</h4>
<%= link_to "Check-in", user_check_in_path(@user) %>

<h4>See Your Current Reservations</h4>
<%= link_to "Current Reservations", user_reservations_path(@user) %>

<h4>See Your Purchase Requests</h4>
<%= link_to "Purchase Requests", user_purchase_requests_path %>