config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books' => 'books#index'
  get '/campus/:campu_id/books/confirm' => 'books#confirm', as: 'book_confirm'
  get '/campus/:campu_id/books' => 'books#campus_index'
  get '/users/:user_id/checkouts' => 'checkouts#user_index', as: 'user_checkouts'
  get '/campus/:campu_id/checkouts' => 'checkouts#campus_index', as: 'campus_checkouts'
  get '/users/:user_id/check_in' => 'checkouts#check_in', as: 'user_check_in'
  get '/books/:book_id/reservations' => 'reservations#book_index', as: 'book_reservations'
  get '/users/:user_id/reservations' => 'reservations#user_index', as: 'user_reservations'
  get '/users/purchase_requests' => 'purchase_requests#user_index', as: 'user_purchase_requests'
  get '/books/search' => 'books#search', as: 'books_search'
  get '/books/results' => 'books#results', as: 'books_results'

  devise_for :users, :controllers => { :registrations => 'plock' }

  resources :campus do
    resources :books, except: [:index], shallow: true do
      resources :reviews, except: [:show, :index], shallow: true
      resources :checkouts, except: [:destroy, :new, :edit], shallow: true
      resources :reservations, only: [:create, :destroy], shallow: true
    end
    resources :purchase_requests, shallow: true
  end

  resources :users, only: [:index, :show]

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/book.rb
class Book < ActiveRecord::Base
  include PgSearch::Model

  pg_search_scope :search_by_all, :against => [:title, :isbn, :author],
                                  :using => {:tsearch => {:prefix => true, :any_word => true}
                                              #:trigram #,
                                              # :dmetaphone
}

  validates_presence_of :isbn

  belongs_to :campus
  has_many :checkouts
  has_many :reviews
  has_many :reservations


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews.includes(:user)
    @current_user = current_user
  end

  def index
    @books = Book.where(confirmed: true).order(:category ,:title)
  end

  def search
    if params[:criteria]
      @books = Book.search_by_all(params[:criteria])
    end
  end

  def campus_index
    @books = Book.where(campus_id: params[:campu_id], confirmed: true).order(:category, :title)
    @campus = @books&.first&.campus || Campus.find(params[:campu_id])
  end

  def new
    @campus = Campus.find params[:campu_id]
    @book = @campus.books.new
  end

  def confirm
    @campus = Campus.find params[:campu_id]
    gb = GetBook.new(params[:isbn])
    @book = gb.find

    unless @book.present?
      flash[:warning] = "Book not found"
      redirect_to new_campu_book_path(@campus)
    end

  end

  def create
    @book = Book.find params[:book][:book_id]
    @book.category = params[:book][:category]
    @book.campus_id = params[:campu_id]
    @book.confirmed = true
    if @book.save
      flash[:notice] = "Book added!"
      redirect_to "/campus/#{params[:campu_id]}/books"
    else
      render :new
    end
  end

  def destroy
    book = Book.find params[:id]
    book.destroy
    respond_to do |format|
      format.html { redirect_to "/campus/#{book.campus.id}/books" }
      format.json { render json: { status: :ok } }
    end
  end

  private

  def set_campus
    @campus = Campus.find params[:campu_id]
  end
end

app/views/books/campus_index.html.erb
<body class="BookCampusIndex">

  <h2>
    Current Books for TIY-<%= @campus.city %>
    <span class="badge" id="book-count"></span>
  </h2>

  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>ISBN</th>
        <th>Subject Area</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |b| %>
      </tr>
        <th><%= b.title %></th>
        <th><%= b.author %></th>
        <th><%= b.isbn %></th>
        <th><%= b.category %></th>
        <th><%= b.status %></th>
        <th class="button-container">
          <%= button_to('Go To Book', book_path(b), class: 'btn btn-xs btn-info', method: :get) %>
        </th>
      </tr>
      <% end %>
    </tbody>
  </table>


  <h3>
    Don't see the book you want?
  </h3>
  <%= button_to('Request new book', new_campu_purchase_request_path(@campus), class: 'btn btn-m btn-warning', method: :get) %>

</body>

app/views/books/confirm.html.erb
<h3>Confirm the book to add to TIY-<%= @campus.city %>'s library</h3>
<div class="container">
  <div class="row">
    <div class="col-lg-2">
      <div> <!--padding-->
        <ul>
        </ul>
      </div>
      <img src="<%= @book.cover_url %>" height="236" width="180" onerror="this.src='/no-cover.gif'" />
    </div>
    <div class="col-lg-7">
      <h3><%= @book.title %></h3>
      <h4>By <%= @book.author  %></h4>
      Summary:
      <ul>
        <li><%= @book.summary  %></li>
      </ul>
      <div class="button-container">
        <%= bootstrap_form_for @book, layout: :inline, url: campu_books_path(@campus), method: :post do |f| %>
          <%= f.select :category, [["general", "general"],
                                   ["ruby", "ruby"],
                                   ["rails", "rails"],
                                   ["html", "html"],
                                   ["css", "css"],
                                   ["javascript", "javascript"],
                                   ["angular", "angular"],
                                   ["react", "react"]],
                                   { label: "Select category:" }, { class: "selectpicker" } %>
          <%= f.hidden_field :book_id, value: @book.id %>
          <button class="btn btn-success btn-sm">Confirm</button>
        <% end %>

        <%= button_to "Reject", new_campu_book_path(@campus), class: "btn btn-warning btn-sm", method: "get" %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<body class="BookIndex">

  <h2>
    Current Books
    <span class="badge" id="book-count"></span>
  </h2>

  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>ISBN</th>
        <th>Subject Area</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |b| %>
      </tr>
        <th><%= b.title %></th>
        <th><%= b.author %></th>
        <th><%= b.isbn %></th>
        <th><%= b.category %></th>
        <th><%= b.status %></th>
        <th class="button-container">
          <%= button_to('Go To Book', book_path(b), class: 'btn btn-xs btn-info', method: :get) %>
        </th>
      </tr>
      <% end %>
    </tbody>
  </table>

</body>

app/views/books/new.html.erb
<h4>Add a book to TIY-<%= @campus.city %>'s library</h4>
<%= bootstrap_form_tag url: book_confirm_path(@campus), method: :get do |f| %>
  <%= f.text_field :isbn, label: "ISBN number (no dashes)" %>
  <%= f.submit %>
<% end %>

app/views/books/search.html.erb
<h4>Search for a book by title, author, or ISBN</h4>

<%= bootstrap_form_tag url: books_search_path, method: :get do |f| %>
  <%= f.text_field :criteria %>
  <button class="btn btn-primary btn-sm">Submit</button>
<% end %>

<% if @books %>
  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>ISBN</th>
        <th>Subject Area</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |b| %>
      </tr>
        <th><%= b.title %></th>
        <th><%= b.author %></th>
        <th><%= b.isbn %></th>
        <th><%= b.category %></th>
        <th><%= b.status %></th>
        <th class="button-container">
          <%= button_to('Go To Book', book_path(b), class: 'btn btn-xs btn-info', method: :get) %>
        </th>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2">
      <div> <!--padding-->
        <ul>
        </ul>
      </div>
      <img src="<%= @book.cover_url %>" height="236" width="180" onerror="this.src='/no-cover.gif'" />
      <div> <!--padding-->
        <ul>
        </ul>
      </div>
      <div class="button-container">
        Status: <%= @book.status %>
        <% if @current_user %> -
          <% if @book.status == "in" %>
            <%= button_to "Checkout", book_checkouts_path(@book), class: "btn btn-info btn-xs" %>
          <% else %>
            <%= button_to "Reserve", book_reservations_path(@book), class: "btn btn-primary btn-xs", data: "#{@book.id}" %>
          <% end %>
          <div> <!--padding-->
            <ul>
            </ul>
          </div>
          <div>
            <%= button_to "Write Review", new_book_review_path(@book), class: "btn btn-success btn-sm", method: "get" %>
          </div>
          <div> <!--padding-->
            <ul>
            </ul>
          </div>
          <div>
            <%= button_to "Delete", book_path(@book), class: "btn btn-danger btn-sm", method: "delete" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-lg-7">
      <h3><%= @book.title %></h3>
      <h4>By <%= @book.author  %></h4>
      Summary:
      <ul>
        <li><%= @book.summary  %></li>
      </ul>
      Raitings:
      <ul>
        <li>Iron Yard (N/A)</li>
      </ul>
    </div>
  </div>
  <h3><font color="crimson">Iron</font>Reviews
    <span class="badge"><%= @reviews.length%></span>
  </h3>
  <% @reviews.each do |rev|%>
    <div class="well">
      <p>"<%= rev.content %>"</p>
      <% if rev.response %>
        <p><i><font color="crimson"><%= rev.response %></font></i></p>
      <% end %>
      <p align="right"><font color="crimson"><%= rev.user.name %></font> on <%=(rev.created_at.in_time_zone('Eastern Time (US & Canada)')).strftime("%B %-d %Y - %I:%M%p EST")%>
        <br>
          <div align="right" class="button-container">
            <%= button_to "Edit", edit_review_path(rev), class: "btn btn-warning btn-sm", method: "get" %>
            <%= button_to "Delete", review_path(rev), class: "btn btn-danger btn-sm", method: "delete" %>
          </div>
      </p>
    </div>
  <% end %>
</div>