config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  get 'books' => 'books#index'
  get '/campus/:campu_id/books/confirm' => 'books#confirm', as: 'book_confirm'
  get '/campus/:campu_id/books' => 'books#campus_index'
  get '/users/:user_id/checkouts' => 'checkouts#user_index', as: 'user_checkouts'
  get '/campus/:campu_id/checkouts' => 'checkouts#campus_index', as: 'campus_checkouts'
  get '/users/:user_id/check_in' => 'checkouts#check_in', as: 'user_check_in'
  get '/books/:book_id/reservations' => 'reservations#book_index', as: 'book_reservations'
  get '/users/:user_id/reservations' => 'reservations#user_index', as: 'user_reservations'
  get '/users/purchase_requests' => 'purchase_requests#user_index', as: 'user_purchase_requests'
  get '/books/search' => 'books#search', as: 'books_search'
  get '/books/results' => 'books#results', as: 'books_results'

  devise_for :users, :controllers => { :registrations => 'plock' }

  resources :campus do
    resources :books, except: [:index], shallow: true do
      resources :reviews, except: [:show, :index], shallow: true
      resources :checkouts, except: [:destroy, :new, :edit], shallow: true
      resources :reservations, only: [:create, :destroy], shallow: true
    end
    resources :purchase_requests, shallow: true
  end

  resources :users, only: [:index, :show]

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @book = Book.find params[:book_id]
    @review = @book.reviews.new(user_id: current_user.id)
  end

  def create
    @book = Book.find params[:book_id]
    @review = @book.reviews.new approved_params
    if @review.save
      flash[:notice] = "Review added!"
      redirect_to @book
    else
      render :new
    end
  end

  def edit
    @review = Review.find params[:id]
  end

  def update
    @review = Review.find params[:id]
    if @review.update approved_params
      flash[:notice] = "Review edited!"
      redirect_to @review.book
    else
      render :edit
    end
  end

  def destroy
    review = Review.find params[:id]
    review.destroy
    flash[:notice] = "Review deleted!"
    redirect_to :back
  end

  private

  def set_campus
    @campus = Campus.find params[:campu_id]
  end

  def approved_params
    params.require(:review).permit(:content, :user_id, :response)
  end

end

app/views/reviews/edit.html.erb
<h4>Edit this review for <%= @review.book.title %></h4>
<%= bootstrap_form_for @review, url: review_path(@review), method: :patch do |f| %>
  <%= f.text_area :content, value: @review.content %>
  <%= f.text_area :response, value: @review.response %>
  <button class="btn btn-primary btn-sm">Submit</button>
<% end %>

app/views/reviews/new.html.erb
<h4>Write a review for <%= @review.book.title %></h4>
<%= bootstrap_form_for @review, url: book_reviews_path(@review.book) do |f| %>
  <%= f.text_area :content, label: " " %>
  <%= f.hidden_field :user_id, value: current_user.id%>
  <button class="btn btn-primary btn-sm">Submit</button>
<% end %>